name: sengthaite_blog
description: "SENGTHAITE_BLOG"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.5.1
  material_design_icons_flutter: ^7.0.7296
  intl: any
  markdown_widget: ^2.3.2+8
  front_matter_ml: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_quill: ^11.5.0
  flutter_svg: ^2.2.3
  path: ^1.9.1
  google_fonts: ^6.2.1
  video_player: ^2.9.1
  markdown: ^7.2.2
  html: ^0.15.4
  dio: ^5.5.0+1
  modal_bottom_sheet: ^3.0.0
  camera: ^0.11.0+2
  device_preview: ^1.3.1
  hive_ce: ^2.15.1
  hive_ce_generator: ^1.9.0
  flutter_html: ^3.0.0-beta.2
  dart_jsonwebtoken: ^3.2.0
  file_picker: ^10.3.3
  pointycastle: ^4.0.0
  flutter_highlight: ^0.7.0
  dart_eval: ^0.8.2
  file_saver: ^0.3.1
  url_launcher: ^6.3.2
  flutter_code_editor: ^0.3.4
  highlight: ^0.7.0
  yaml: ^3.1.3
  barcode_widget: ^2.0.4
  barcode_image: ^2.0.3
  pdf: ^3.11.3
  file_selector: ^1.1.0
  image: ^4.5.4
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.11.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/content_icons/
    - assets/contents/
    - assets/contents/database/
    - assets/contents/biography/
    - assets/contents/general/
    - assets/contents/csharp/
    - assets/contents/llvm/
    - assets/contents/angular/
    - assets/contents/kotlin/
    - assets/contents/cli/
    - assets/contents/reverse_engineer/
    - assets/contents/ios/
    - assets/contents/swift/
    - assets/contents/android/
    - assets/contents/maths/
    - assets/contents/os/
    - assets/contents/cambodia/
    - assets/contents/tool/
    # - assets/project_icons/
    - assets/autogen_meta/
    - assets/tool_icons/
    

targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          tree_shake: true
